-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE DIGITAL_ECONOMY_RIDE_HAILING;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.PLATFORMS (
  PLATFORM_ID VARCHAR(20) NOT NULL, PLATFORM_NAME VARCHAR(200), CATEGORY VARCHAR(50), REGION VARCHAR(50), USERS_TOTAL INT, GMV_MONTHLY FLOAT, STATUS VARCHAR(20), LAUNCHED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
  TXN_ID VARCHAR(30) NOT NULL, ACCOUNT_ID VARCHAR(20), TXN_TYPE VARCHAR(30), AMOUNT FLOAT, CURRENCY VARCHAR(5), COUNTERPARTY VARCHAR(100), TXN_DATE TIMESTAMP, STATUS VARCHAR(20), CHANNEL VARCHAR(30), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.USERS (
  USER_ID VARCHAR(20) NOT NULL, PLATFORM_ID VARCHAR(20), USER_TYPE VARCHAR(20), CITY VARCHAR(50), REGISTRATION_DATE DATE, TOTAL_TRANSACTIONS INT, LIFETIME_VALUE FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MERCHANTS (
  MERCHANT_ID VARCHAR(20) NOT NULL, PLATFORM_ID VARCHAR(20), MERCHANT_NAME VARCHAR(200), CATEGORY VARCHAR(50), CITY VARCHAR(50), RATING FLOAT, TOTAL_SALES FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
