-- Generated from generator/demo_specs/aws-indonesia-digital-economy-ride-hailing.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-digital-economy-ride-hailing
-- This is the schema that is actually deployed for ID_DIGITAL_ECONOMY_RIDE_HAILING.

-- Alerts fire on the bottom tail of Driver Utilization
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_DRIVER_UTILIZATION) AS T
  FROM RAW.DEMAND_EVENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_DRIVER_UTILIZATION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_DRIVER_UTILIZATION), 2) AS AVG_DRIVER_UTILIZATION,
  ROUND(AVG(f.KPI_AVG_WAIT_TIME), 2) AS AVG_WAIT_TIME,
  ROUND(AVG(f.KPI_ETA_ACCURACY), 2) AS AVG_ETA_ACCURACY,
  ROUND(AVG(f.KPI_CANCELLATION_RATE), 2) AS AVG_CANCELLATION_RATE
FROM RAW.DEMAND_EVENTS f
JOIN RAW.ZONE_CONFIG e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_DRIVER_UTILIZATION), 2) AS AVG_DRIVER_UTILIZATION,
  ROUND(AVG(f.KPI_AVG_WAIT_TIME), 2) AS AVG_WAIT_TIME,
  ROUND(AVG(f.KPI_ETA_ACCURACY), 2) AS AVG_ETA_ACCURACY,
  ROUND(AVG(f.KPI_CANCELLATION_RATE), 2) AS AVG_CANCELLATION_RATE
FROM RAW.DEMAND_EVENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_DRIVER_UTILIZATION) AS KPI_DRIVER_UTILIZATION, AVG(KPI_AVG_WAIT_TIME) AS KPI_AVG_WAIT_TIME, AVG(KPI_ETA_ACCURACY) AS KPI_ETA_ACCURACY, AVG(KPI_CANCELLATION_RATE) AS KPI_CANCELLATION_RATE FROM RAW.DEMAND_EVENTS),
     en AS (SELECT SUM(KPI_RIDES_MTD) AS KPI_RIDES_MTD, SUM(KPI_ACTIVE_DRIVERS) AS KPI_ACTIVE_DRIVERS, SUM(KPI_SURGE_PRICING_ACTIVE) AS KPI_SURGE_PRICING_ACTIVE FROM RAW.ZONE_CONFIG)
  SELECT 1 AS SORT_ORDER, 'Rides (MTD)' AS TITLE, KPI_RIDES_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_RIDES_MTD) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Driver Utilization' AS TITLE, KPI_DRIVER_UTILIZATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DRIVER_UTILIZATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Avg Wait Time' AS TITLE, KPI_AVG_WAIT_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_WAIT_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'min' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Drivers' AS TITLE, KPI_ACTIVE_DRIVERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_DRIVERS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Surge Pricing Active' AS TITLE, KPI_SURGE_PRICING_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SURGE_PRICING_ACTIVE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'ETA Accuracy' AS TITLE, KPI_ETA_ACCURACY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ETA_ACCURACY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Cancellation Rate' AS TITLE, KPI_CANCELLATION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CANCELLATION_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
