-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT zone.ID AS ENTITY_ID, zone.NAME AS ENTITY_NAME,
       zone.REGION, zone.CATEGORY, zone.CONGESTION_TIER, zone.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.REQUEST_COUNT) AS REQUEST_COUNT,
       SUM(observation.TRIP_COUNT) AS TRIP_COUNT,
       SUM(observation.UNFULFILLED_COUNT) AS UNFULFILLED_COUNT,
       SUM(observation.CANCELLED_COUNT) AS CANCELLED_COUNT,
       SUM(observation.GMV_IDR) AS GMV_IDR,
       SUM(observation.SHORTAGE_HOURS) AS SHORTAGE_HOURS,
       COUNT_IF(observation.SHORTAGE_HOURS > 0) AS SHORTAGE_DAYS,
       SUM(observation.PAYOUT_DUE) AS PAYOUT_DUE,
       SUM(observation.PAYOUT_SETTLED) AS PAYOUT_SETTLED,
       100.0 * SUM(observation.TRIP_COUNT) / NULLIF(SUM(observation.REQUEST_COUNT), 0) AS FULFILLMENT_PCT,
       100.0 * SUM(observation.CANCELLED_COUNT) / NULLIF(SUM(observation.REQUEST_COUNT), 0) AS CANCELLATION_PCT,
       100.0 * SUM(observation.PAYOUT_SETTLED) / NULLIF(SUM(observation.PAYOUT_DUE), 0) AS PAYOUT_ON_TIME_PCT,
       AVG(observation.AVG_SURGE_MULT) AS AVG_SURGE_MULT,
       AVG(observation.AVG_PICKUP_ETA_MIN) AS AVG_PICKUP_ETA_MIN,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.ZONE_DAILY observation
JOIN RAW.ZONES zone ON zone.ID = observation.ENTITY_ID
GROUP BY zone.ID, zone.NAME, zone.REGION, zone.CATEGORY, zone.CONGESTION_TIER, zone.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(REQUEST_COUNT) AS REQUEST_COUNT, SUM(TRIP_COUNT) AS TRIP_COUNT,
       SUM(UNFULFILLED_COUNT) AS UNFULFILLED_COUNT, SUM(SHORTAGE_HOURS) AS SHORTAGE_HOURS,
       SUM(GMV_IDR) AS GMV_IDR,
       100.0 * SUM(TRIP_COUNT) / NULLIF(SUM(REQUEST_COUNT), 0) AS FULFILLMENT_PCT
FROM RAW.ZONE_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.CAUSE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT SHORTAGE_CAUSE, COUNT(*) AS SHORTAGE_DAYS,
       SUM(SHORTAGE_HOURS) AS SHORTAGE_HOURS,
       SUM(UNFULFILLED_COUNT) AS UNFULFILLED_COUNT,
       SUM(REQUEST_COUNT) AS REQUEST_COUNT,
       100.0 * SUM(UNFULFILLED_COUNT) / NULLIF(SUM(REQUEST_COUNT), 0) AS UNFULFILLED_PCT
FROM RAW.ZONE_DAILY
WHERE SHORTAGE_HOURS > 0
GROUP BY SHORTAGE_CAUSE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(REQUEST_COUNT) AS REQUESTS, SUM(TRIP_COUNT) AS TRIPS,
         SUM(UNFULFILLED_COUNT) AS UNFULFILLED, SUM(CANCELLED_COUNT) AS CANCELLED,
         SUM(SHORTAGE_HOURS) AS SHORTAGE_HOURS, COUNT_IF(SHORTAGE_HOURS > 0) AS SHORTAGE_DAYS,
         SUM(GMV_IDR) AS GMV_IDR, SUM(PAYOUT_DUE) AS PAYOUT_DUE, SUM(PAYOUT_SETTLED) AS PAYOUT_SETTLED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.ZONE_DAILY
), book AS (SELECT COUNT(*) AS ZONE_COUNT FROM RAW.ZONES),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.DRIVER_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Fulfillment Rate' AS TITLE,
         100.0 * TRIPS / NULLIF(REQUESTS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Unfulfilled Requests', UNFULFILLED, '' FROM observations
  UNION ALL SELECT 3, 'Supply Shortage Hours', SHORTAGE_HOURS, '' FROM observations
  UNION ALL SELECT 4, 'Rider Cancellation Rate', 100.0 * CANCELLED / NULLIF(REQUESTS, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Shortage Zone-Days', SHORTAGE_DAYS, '' FROM observations
  UNION ALL SELECT 6, 'GMV (IDR B)', GMV_IDR / 1e9, '' FROM observations
  UNION ALL SELECT 7, 'Trips Completed', TRIPS, '' FROM observations
  UNION ALL SELECT 8, 'Driver Payout On-Time Rate', 100.0 * PAYOUT_SETTLED / NULLIF(PAYOUT_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Zones Monitored', ZONE_COUNT, '' FROM book
  UNION ALL SELECT 10, 'Driver Document Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Driver Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.CAUSE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
