-- Supply-shortage risk scoring and unfulfilled-request forecast over the synthetic snapshot.
-- Predicts P(supply shortage in the zone in the next 7 days) per zone and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.SHORTAGE_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, z.CATEGORY, z.CONGESTION_TIER, z.ZONE_AGE_YEARS,
       r.AVG_SURGE_MULT, r.AVG_PICKUP_ETA_MIN,
       AVG(r.AVG_PICKUP_ETA_MIN) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS PICKUP_ETA_7D,
       SUM(r.SHORTAGE_HOURS) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS SHORTAGE_HOURS_30D,
       IFF(SUM(r.SHORTAGE_HOURS) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'SHORTAGE', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.ZONE_DAILY r JOIN RAW.ZONES z ON z.ID = r.ENTITY_ID
-- City-wide flooding is not zone-driven, so those days are excluded from training.
WHERE r.SHORTAGE_CAUSE <> 'City-wide flooding';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.SHORTAGE_TRAIN AS
SELECT CATEGORY, CONGESTION_TIER, ZONE_AGE_YEARS, AVG_SURGE_MULT, AVG_PICKUP_ETA_MIN, PICKUP_ETA_7D, SHORTAGE_HOURS_30D, LABEL
FROM ML.SHORTAGE_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.SHORTAGE_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, CONGESTION_TIER, ZONE_AGE_YEARS, AVG_SURGE_MULT, AVG_PICKUP_ETA_MIN, PICKUP_ETA_7D, SHORTAGE_HOURS_30D, LABEL
FROM ML.SHORTAGE_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.SHORTAGE_RISK_MODEL(
  INPUT_DATA => TABLE(ML.SHORTAGE_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.SHORTAGE_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.SHORTAGE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'CONGESTION_TIER', CONGESTION_TIER, 'ZONE_AGE_YEARS', ZONE_AGE_YEARS,
           'AVG_SURGE_MULT', AVG_SURGE_MULT, 'AVG_PICKUP_ETA_MIN', AVG_PICKUP_ETA_MIN,
           'PICKUP_ETA_7D', PICKUP_ETA_7D, 'SHORTAGE_HOURS_30D', SHORTAGE_HOURS_30D)):probability:SHORTAGE::FLOAT AS P
  FROM ML.SHORTAGE_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'SHORTAGE', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'SHORTAGE', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'SHORTAGE', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'SHORTAGE', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per zone (label unknown, so excluded from features).
CREATE TABLE ML.SHORTAGE_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.SHORTAGE_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.SHORTAGE_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'CONGESTION_TIER', CONGESTION_TIER, 'ZONE_AGE_YEARS', ZONE_AGE_YEARS,
           'AVG_SURGE_MULT', AVG_SURGE_MULT, 'AVG_PICKUP_ETA_MIN', AVG_PICKUP_ETA_MIN,
           'PICKUP_ETA_7D', PICKUP_ETA_7D, 'SHORTAGE_HOURS_30D', SHORTAGE_HOURS_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:SHORTAGE::FLOAT, 4) AS SHORTAGE_PROB_7D,
       CASE WHEN P:probability:SHORTAGE::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:SHORTAGE::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Marketplace-wide unfulfilled-request forecast (14 days) from the daily series, for driver incentive planning.
CREATE VIEW ML.DAILY_UNFULFILLED AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(UNFULFILLED_COUNT)::FLOAT AS UNFULFILLED_COUNT
FROM RAW.ZONE_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.UNFULFILLED_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_UNFULFILLED),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'UNFULFILLED_COUNT'
);

CREATE TABLE ML.UNFULFILLED_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS UNFULFILLED_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.UNFULFILLED_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
