-- ============================================================================
-- 99_RESET.SQL — Reset Ride-Hailing & Super-App Analytics to clean demo state
-- ============================================================================
USE DATABASE RIDE_HAILING_ANALYTICS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_DEMAND SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEMAND SUSPEND;
ALTER TASK IF EXISTS APP.TASK_OPTIMIZE_PRICING SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.DEMAND_SUPPLY_BALANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.FULFILLMENT_METRICS REFRESH;
ALTER DYNAMIC TABLE CURATED.DRIVER_ECONOMICS REFRESH;
ALTER DYNAMIC TABLE CURATED.PRICING_EFFECTIVENESS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM RIDE_HAILING_ANALYTICS.RAW.TRIPS → 100000000
-- SELECT COUNT(*) FROM RIDE_HAILING_ANALYTICS.RAW.DRIVERS → 2000000
-- SELECT COUNT(*) FROM RIDE_HAILING_ANALYTICS.RAW.DEMAND_EVENTS → 500000000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_OPTIMIZE_PRICING RESUME;
ALTER TASK IF EXISTS APP.TASK_FORECAST_DEMAND RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_DEMAND RESUME;
